Restored toolsUI-4.1.jar since toolsUI-4.2.jar does not work with threddsBrowser (java.lang.NoClassDefFoundError: thredds/catalog/ui/CatalogTreeView)
git-svn-id: file:///home/users/tmap/svn/repos/ferret/branches/pyferret@12418 fdbf22ae-c210-0410-be80-ca943da6b8f8